apiVersion: apps/v1
kind: Deployment
metadata:
  name: odm-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: bitnami/redis:7.0-debian-12
        ports:
        - containerPort: 6379
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"

---

apiVersion: v1
kind: Service
metadata:
  name: odm-broker
spec:
  selector:
    app: broker
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

